FROM ubuntu:20.04

ENV CODE_RELEASE=4.95.3
ENV DEBIAN_FRONTEND="noninteractive"
ENV HOME="/config"

RUN \
  echo "**** install runtime dependencies ****" && \
  apt-get update && \
  apt-get install -y \
    git \
    curl \
    libatomic1 \
    nano \
    net-tools \
    sudo && \
  echo "**** install code-server ****" && \
  if [ -z ${CODE_RELEASE+x} ]; then \
    CODE_RELEASE=$(curl -sX GET https://api.github.com/repos/coder/code-server/releases/latest \
      | awk '/tag_name/{print $4;exit}' FS='[""]' | sed 's|^v||'); \
  fi && \
  mkdir -p /app/code-server && \
  curl -o \
    /tmp/code-server.tar.gz -L \
    "https://github.com/coder/code-server/releases/download/v${CODE_RELEASE}/code-server-${CODE_RELEASE}-linux-arm64.tar.gz" && \
  tar xf /tmp/code-server.tar.gz -C \
    /app/code-server --strip-components=1 && \
  echo "**** clean up ****" && \
  apt-get clean && \
  rm -rf \
    /config/* \
    /tmp/* \
    /var/lib/apt/lists/* \
    /var/tmp/*


# create user alice
RUN useradd -m -s /bin/bash alice
RUN usermod -aG sudo alice
RUN mkdir -p /config/workspace
# add local files
COPY /root /
## add alice to sudoers
RUN echo "alice ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

## set /config/workspace as alice's ownership
RUN chown -R alice:alice /config/workspace

# install custom packages
__INSTALL_CUSTOM_PACKAGES__


## set alice as the default user
USER alice

# ports and volumes
EXPOSE 8443

COPY start.sh /start.sh
CMD ["bash", "/start.sh"]